### ISSUE TITLE
Update links to use new domain name (biotechcoder.com)

### ISSUE THREAD

**Issue by andrewholgate** [biotechcoder/sphinx-themes#6]
The links being used are currently pointing to the old domain name (http://vkvn.github.io/) and need to be updated to use the new domain name (http://biotechcoder.com).

For example:
- http://biotechcoder.com/sphinx-themes/
- http://biotechcoder.com/sphinx-themes/solar/html/index.html
- etc.

**Comment by biotechcoder** [comment]
Fixed. Thanks!

**Comment by andrewholgate** [comment]
Great, looks better.

There's just the last remaining link in the Github project description to update:

```
Themes for Python Sphinx documentation projects. A demo is available at http://vkvn.github.io/sphinx-themes
```

**Comment by biotechcoder** [comment]
Missed that! :)  Thanks again..
